import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nest", 
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}> 
        <ThemeProvider attribute="class" defaultTheme="dark" >
        <main>{children}</main>

        <footer><p>Project Management Platform</p></footer>
        </ThemeProvider>
        
      </body>
    </html>
  );
}
